Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using E_Players_Asp_Net_Core.Interfaces;

namespace E_Players_Asp_Net_Core.Models
{
    public class Equipe : BaseEplayers , IEquipe
    {
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }
        private const string PATH = "Database/equipe.csv";

        /// <summary>
        /// Lê todas as linhas do csv
        /// </summary>
        /// <param name="e">lista de equiupes</param>
        public void Create(Equipe e)
        {
            string[] linha = { Prepare(e) };
            File.AppendAllLines(PATH, linha);
        }
        private string Prepare(Equipe e){
            return $"{e.IdEquipe};{e.Nome};{e.Imagem}";
        }

        public List<Equipe> ReadAll()
        {
            List<Equipe> equipes = new List<Equipe>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Equipe equipe = new Equipe();
                equipe.IdEquipe = Int32.Parse(linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add(equipe);
            }
            return equipes;
        }

        public void Update(Equipe e)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == e.IdEquipe.ToString());
            linhas.Add( Prepare(e) );
            RewriteCSV(PATH, linhas);
        }

        public void Delete(int id)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == id.ToString());
            RewriteCSV(PATH, linhas);
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using E_Players_Asp_Net_Core.Models;
using Microsoft.AspNetCore.Http;

namespace E_Players_Asp_Net_Core.Controllers
{
    public class EquipeController : Controller
    {
        Equipe equipeModel = new Equipe();

        public IActionResult Index()
        {
            ViewBag.Equipes = equipeModel.ReadAll(); 
            return View();
        }
        public IActionResult Cadastrar(IFormCollection form)
        {
            Equipe novaEquipe = new Equipe();
            novaEquipe.IdEquipe = Int32.Parse( form ["IdEquipe"] );
            novaEquipe.Nome = form["Nome"];
            

             // Upload Início
            var file    = form.Files[0];
            var folder  = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

            if(file != null)
            {
                if(!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))  
                {  
                    file.CopyTo(stream);  
                }
                novaEquipe.Imagem   = file.FileName;
            }
            else
            {
                novaEquipe.Imagem   = "padrao.png";
            }
            // Upload Final

            equipeModel.Create(novaEquipe);
            ViewBag.Equipes = equipeModel.ReadAll();
            return LocalRedirect("~/Equipe");
        }
        [Route("{id}")]
        public IActionResult Excluir(int id)
        {
            equipeModel.Delete(id);
            return LocalRedirect("~/Equipe");

        }

    }
}

Views/Equipe/Index.cshtml
 @model Equipe
    @{
        ViewData["Title"] = "Equipes";
    }

     <div class="titulo_pagina">
            <h1>cadastro de @ViewData["Title"]</h1>
    </div>

<form class="cadastro" action="@Url.Action("Cadastrar")" method="post" enctype="multipart/form-data">

    <div class="campo">
    <label for="IdEquipe">IdEquipe</label>
    <input type="text" name="IdEquipe" id="IdEquipe">
    </div>

    <div class="campo">
    <label for="Nome">Nome</label>
    <input type="text" name="Nome" id="Nome">
    </div>

    <div class="campo">
    <label for="Imagem">Imagem</label>
    <input type="file" name="Imagem" id="Imagem">
    </div>

    <button  class="gradient btn"  type="submit">Cadastrar</button>
</form>

<table class="table table-responsive table-striped">
    <thead>
        <th>Id</th>
        <th>Nome</th>
        <th>Imagem</th>
        <th>Ações</th>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Equipes)
        {
            <tr>
                <td>@item.IdEquipe</td>
                <td>@item.Nome</td>
                <td>
                    <img src="img/Equipes/@item.Imagem" alt="Imagem da Euipe @item.Nome " />
                </td>
                <td>
                     <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipe" asp-action="Excluir" asp-route-id="@item.IdEquipe">
                                <i class=" fa fa-trash"></i>
                            </a>
                        </li>
                </td>

            </tr>
            
        }
    </tbody>

</table>